server:
  port: ${SERVER_PORT:8080}
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    url: ${DB_JDBC_URL:jdbc:h2:mem:dna_checker_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}

